#!/bin/bash

# Function to display CPU information
get_cpu_info() {
    lscpu
}

# Function to display memory information
get_memory_info() {
    free
}

# Function to create a new user
create_user() {
    if [ -z "$1" ]; then
        echo "Error: Please provide a username."
        exit 1
    fi

    sudo useradd -m "$1"
    sudo passwd "$1"
}

# Function to list users
list_users() {
    if [ "$1" == "--sudo-only" ]; then
        grep -Po '^sudo.+:\K.*$' /etc/group | tr ',' '\n'
    else
        cut -d: -f1 /etc/passwd
    fi
}

# Function to get file information
get_file_info() {
    if [ -z "$1" ]; then
        echo "Error: Please provide a filename."
        exit 1
    fi

    file="$1"

    size=$(stat -c %s "$file")
    permissions=$(stat -c %A "$file")
    owner=$(stat -c %U "$file")
    last_modified=$(stat -c %y "$file")

    echo "File: $file"
    echo "Access: $permissions"
    echo "Size(B): $size"
    echo "Owner: $owner"
    echo "Modify: $last_modified"
}

# Main script
case "$1" in
    "cpu")
        case "$2" in
            "getinfo")
                get_cpu_info
                ;;
            *)
                echo "Error: Invalid CPU command."
                exit 1
                ;;
        esac
        ;;
    "memory")
        case "$2" in
            "getinfo")
                get_memory_info
                ;;
            *)
                echo "Error: Invalid memory command."
                exit 1
                ;;
        esac
        ;;
    "user")
        case "$2" in
            "create")
                create_user "$3"
                ;;
            "list")
                list_users "$3"
                ;;
            *)
                echo "Error: Invalid user command."
                exit 1
                ;;
        esac
        ;;
    "file")
        case "$2" in
            "getinfo")
                shift
                get_file_info "$@"
                ;;
            *)
                echo "Error: Invalid file command."
                exit 1
                ;;
        esac
        ;;
    "--version")
        echo "internsctl v0.1.0"
        ;;
    "--help")
        echo "Help: TODO"
        ;;
    *)
        echo "Error: Invalid command."
        exit 1
        ;;
esac
